const defaultEntries = [
  { id: 1, type: 'service', title: 'Olje og oljefilter', date: '2026-08-23', mileage: '82 400 km', place: 'Møller Bil Lillestrøm', cost: 2890 },
  { id: 2, type: 'repair', title: 'Byttet bremseskiver foran', date: '2026-04-14', mileage: '76 890 km', place: 'Mekonomen Skedsmo', cost: 6490 },
  { id: 3, type: 'tire', title: 'Sommerdekk på', date: '2026-04-07', mileage: '76 430 km', place: 'Hjemme', cost: 0 },
];
const typeInfo = { service: ['🔧', 'service'], repair: ['🛠️', 'repair'], tire: ['🛞', 'tire'], other: ['📌', 'other'] };
const translations = {
  nb: { myVehicle: 'MIN BIL', entries: 'hendelser', latestService: 'siste service', decoderTitle: 'Feilkodehjelp', decoderIntro: 'Lim inn en feilkode fra OBD-leseren, så får du en enkel forklaring og forslag til neste steg.', dtcPlaceholder: 'For eksempel P0420', decodeButton: 'Forklar kode', inputHint: 'Støtter generiske P-, B-, C- og U-koder. Merke-spesifikke koder kan variere.', history: 'HISTORIKK', logbook: 'Bilens loggbok', filter: 'Filter', all: 'Alle', service: 'Service', repair: 'Reparasjon', tire: 'Dekk', other: 'Annet', noMatches: 'Ingen treff', noMatchesHint: 'Prøv et annet filter, eller legg til en ny hendelse.', add: 'Legg til', deleteEntry: 'Slett hendelse', deleteConfirm: 'Slette denne hendelsen permanent?', symptoms: 'Symptomer', causes: 'Vanlige årsaker', solution: 'Hva kan løse det', loading: 'Henter og oversetter forklaring fra OBDex…', translating: 'Oversetter…', invalidCode: 'Bruk en femtegns OBD-II-kode, for eksempel', genericCode: 'Generisk OBD-II-feilkode', saveDtc: '＋ Lagre i bilens loggbok', savedDtc: '✓ Lagret i bilens loggbok', categories: { P: 'Motor og drivlinje', B: 'Karosseri og komfort', C: 'Chassis', U: 'Kommunikasjon og nettverk' } },
  en: { myVehicle: 'MY CAR', entries: 'entries', latestService: 'latest service', decoderTitle: 'Trouble code help', decoderIntro: 'Paste a code from your OBD reader to get a clear explanation and suggested next steps.', dtcPlaceholder: 'For example P0420', decodeButton: 'Explain code', inputHint: 'Supports generic P, B, C and U codes. Manufacturer-specific codes may vary.', history: 'HISTORY', logbook: 'Vehicle logbook', filter: 'Filter', all: 'All', service: 'Service', repair: 'Repair', tire: 'Tires', other: 'Other', noMatches: 'No matches', noMatchesHint: 'Try another filter or add a new entry.', add: 'Add', deleteEntry: 'Delete entry', deleteConfirm: 'Permanently delete this entry?', symptoms: 'Symptoms', causes: 'Common causes', solution: 'What may fix it', loading: 'Loading OBDex explanation…', translating: 'Loading…', invalidCode: 'Use a five-character OBD-II code, for example', genericCode: 'Generic OBD-II trouble code', saveDtc: '＋ Save to vehicle logbook', savedDtc: '✓ Saved to vehicle logbook', categories: { P: 'Powertrain', B: 'Body and comfort', C: 'Chassis', U: 'Communication and network' } },
  
};
Object.assign(translations.nb, {
  maintenance: 'VEDLIKEHOLD', remindersTitle: 'Kommende påminnelser', edit: 'Endre', nextService: 'Neste service', changeSummerTires: 'Bytt til sommerdekk', changeWinterTires: 'Bytt til vinterdekk', addServiceToStart: 'Legg inn en service for å starte intervallet', overdue: 'Forfalt', thisWeek: 'Denne uken', today: 'I dag', inDays: 'Om {days} dager',
  workshop: 'VERKSTED', workshopTitle: 'Finn verksted', locateMe: '⌖ Finn nær meg', locating: 'Søker...', searchingWorkshops: 'Søker etter verksteder innen 15 km...', dealer: 'Forhandler', independent: 'Selvstendig', workshopInitial: 'Bruk posisjonen din for å se verksteder i nærheten.', workshopFound: '{count} verksteder funnet. Trykk på et verksted for å åpne kartet.', noWorkshops: 'Fant ingen registrerte verksteder i nærheten.', workshopError: 'Kunne ikke hente verksteder akkurat nå. Prøv igjen om litt.', noWorkshopMatches: 'Ingen verksteder passer med dette filteret.', addressUnavailable: 'Adresse ikke oppgitt', mapAttribution: 'Kartdata © OpenStreetMap-bidragsytere', locationUnsupported: 'Posisjonstjenester støttes ikke i denne nettleseren.', gettingLocation: 'Henter posisjonen din...', locationDenied: 'Posisjonstillatelse er avslått. Tillat posisjon for AutoLog i nettleser- eller iPhone-innstillingene.', locationUnavailable: 'Posisjon er tillatt, men enheten kan ikke levere en nåværende posisjon. Sjekk at Stedstjenester er på, og prøv igjen.', locationTimeout: 'Det tok for lang tid å hente posisjonen. Prøv igjen når du har bedre dekning.',
  newEntry: 'NY REGISTRERING', whatDid: 'Hva gjorde du?', type: 'Type', entryTitle: 'Hva ble gjort?', titlePlaceholder: 'F.eks. Olje og oljefilter', date: 'Dato', mileage: 'Kilometerstand', mileagePlaceholder: '82 500', place: 'Hvor?', placePlaceholder: 'F.eks. Møller Bil', cost: 'Kostnad (kr)', note: 'Notat', optional: 'valgfritt', notePlaceholder: 'Deler, garanti eller noe du vil huske', attachments: 'Vedlegg', attachmentHint: 'Bilder og PDF-kvitteringer lagres på denne enheten.', saveEntry: 'Lagre registrering',
  vehicle: 'BIL', editVehicle: 'Endre bil', vehicleModel: 'Bilmodell', yearRegistration: 'År og registreringsnummer', saveVehicle: 'Lagre bil', newVehicle: 'NY BIL', addToVehicles: 'Legg til i mine biler', vehiclePlaceholder: 'F.eks. Volkswagen ID.4', metaPlaceholder: 'F.eks. 2024 · EV 12345',
  reminders: 'Påminnelser', reminderHelp: 'Service beregnes fra siste registrerte service. Dekkskift følger månedene du velger.', serviceEveryMonths: 'Service hver (måneder)', serviceEveryKm: 'Service hver (km)', summerTiresMonth: 'Sommerdekk (måned)', winterTiresMonth: 'Vinterdekk (måned)', march: 'Mars', april: 'April', may: 'Mai', september: 'September', october: 'Oktober', november: 'November', saveReminders: 'Lagre påminnelser',
  homeScreen: 'HJEMSKJERM', chooseWidgets: 'Velg widgets', widgetHelp: 'Velg det du vil ha på startsiden. Du kan endre dette når som helst.', remindersWidget: 'Påminnelser', remindersWidgetHint: 'Service og dekkskift', logbookWidget: 'Loggbok', logbookWidgetHint: 'Bilens hendelser og kostnader', obdWidget: 'OBD-leser', obdWidgetHint: 'Forklaring av feilkoder', mapWidget: 'Kart og verksted', mapWidgetHint: 'Finn verksteder i nærheten', saveHome: 'Lagre hjemskjerm',
  documents: 'Dokumenter', noAttachments: 'Ingen vedlegg', noAttachmentsHint: 'Ingen vedlegg på denne hendelsen.', addAttachment: '＋ Legg til vedlegg', openingAttachment: 'Åpne', attachmentSaving: 'Lagrer...', attachmentSizeError: 'Hvert vedlegg kan være maksimalt 10 MB.', attachmentSaveError: 'Vedleggene kunne ikke lagres på denne enheten.',
  account: 'KONTO', loginSync: 'Logg inn og synk', accountIntro: 'En AutoLog-konto lar deg synkronisere biler, hendelser og vedlegg sikkert mellom enhetene dine.', accountUnavailable: 'Pålogging er ikke satt opp', accountUnavailableHint: 'Denne versjonen bruker foreløpig bare lokal lagring på enheten.', login: 'Logg inn', information: 'INFORMASJON', privacyTerms: 'Personvern og vilkår', privacy: 'Personvern', privacyTextOne: 'Bilinformasjon, hendelser, påminnelser og vedlegg lagres lokalt på enheten din. AutoLog oppretter ingen konto og sender ikke disse dataene til en egen server i denne versjonen.', privacyTextTwo: 'OBD-oppslag og verkstedsøk bruker eksterne tjenester når du selv ber om det. Tjenestene mottar bare opplysninger som er nødvendige for forespørselen, som feilkode eller posisjon.', terms: 'Vilkår', termsTextOne: 'AutoLog er et hjelpemiddel for oversikt. Påminnelser og feilkodeforklaringer erstatter ikke verkstedets vurdering, bilprodusentens serviceprogram eller sikkerhetsvarsler.', termsTextTwo: 'Du er ansvarlig for å ta backup av lokale data. Ved sletting av nettleserdata eller appdata kan lokalt lagret informasjon gå tapt.', menu: 'MENY', tools: 'Verktøy', myCarsHint: 'Bytt, legg til eller fjern biler', loginHint: 'Synk mellom enhetene dine', language: 'Språk', languageHint: 'Velg språk for AutoLog', privacyTermsHint: 'Hvordan AutoLog behandler data', close: 'Lukk', backHome: 'Tilbake til hjem', backMenu: 'Tilbake til meny', customizeHome: 'Tilpass hjemskjerm', moreOptions: 'Flere valg', deleteVehicle: 'Slett aktiv bil', deleteVehicleConfirm: 'Slette {name} og alle registreringene permanent?', appTitle: 'AutoLog — serviceloggen din', selectedVehicle: 'Valgt bil', overview: 'Oversikt', obdInput: 'OBD-feilkode', editVehicleInfo: 'Endre bilinformasjon', nok: 'kr'
});
Object.assign(translations.en, {
  maintenance: 'MAINTENANCE', remindersTitle: 'Upcoming reminders', edit: 'Edit', nextService: 'Next service', changeSummerTires: 'Switch to summer tires', changeWinterTires: 'Switch to winter tires', addServiceToStart: 'Add a service entry to start the interval', overdue: 'Overdue', thisWeek: 'This week', today: 'Today', inDays: 'In {days} days',
  workshop: 'WORKSHOPS', workshopTitle: 'Find a workshop', locateMe: '⌖ Find near me', locating: 'Searching...', searchingWorkshops: 'Searching for workshops within 15 km...', dealer: 'Dealer', independent: 'Independent', workshopInitial: 'Use your location to find workshops nearby.', workshopFound: '{count} workshops found. Tap a workshop to open the map.', noWorkshops: 'No registered workshops found nearby.', workshopError: 'Could not load workshops right now. Please try again shortly.', noWorkshopMatches: 'No workshops match this filter.', addressUnavailable: 'Address not provided', mapAttribution: 'Map data © OpenStreetMap contributors', locationUnsupported: 'Location services are not supported by this browser.', gettingLocation: 'Getting your location...', locationDenied: 'Location permission was denied. Allow location access for AutoLog in your browser or iPhone settings.', locationUnavailable: 'Location is allowed, but the device cannot provide a current location. Check that Location Services is enabled and try again.', locationTimeout: 'Getting your location took too long. Try again with better coverage.',
  newEntry: 'NEW ENTRY', whatDid: 'What did you do?', type: 'Type', entryTitle: 'What was done?', titlePlaceholder: 'For example, oil and oil filter', date: 'Date', mileage: 'Mileage', mileagePlaceholder: '82,500', place: 'Where?', placePlaceholder: 'For example, Moller Bil', cost: 'Cost (NOK)', note: 'Note', optional: 'optional', notePlaceholder: 'Parts, warranty, or anything to remember', attachments: 'Attachments', attachmentHint: 'Images and PDF receipts are stored on this device.', saveEntry: 'Save entry',
  vehicle: 'VEHICLE', editVehicle: 'Edit vehicle', vehicleModel: 'Vehicle model', yearRegistration: 'Year and registration number', saveVehicle: 'Save vehicle', newVehicle: 'NEW VEHICLE', addToVehicles: 'Add to my vehicles', vehiclePlaceholder: 'For example, Volkswagen ID.4', metaPlaceholder: 'For example, 2024 · EV 12345',
  reminders: 'Reminders', reminderHelp: 'Service is calculated from the most recent service entry. Tire changes follow the months you choose.', serviceEveryMonths: 'Service every (months)', serviceEveryKm: 'Service every (km)', summerTiresMonth: 'Summer tires (month)', winterTiresMonth: 'Winter tires (month)', march: 'March', april: 'April', may: 'May', september: 'September', october: 'October', november: 'November', saveReminders: 'Save reminders',
  homeScreen: 'HOME SCREEN', chooseWidgets: 'Choose widgets', widgetHelp: 'Choose what you want on your home screen. You can change this anytime.', remindersWidget: 'Reminders', remindersWidgetHint: 'Service and tire changes', logbookWidget: 'Logbook', logbookWidgetHint: 'Vehicle entries and costs', obdWidget: 'OBD reader', obdWidgetHint: 'Trouble code explanations', mapWidget: 'Map and workshops', mapWidgetHint: 'Find workshops nearby', saveHome: 'Save home screen',
  documents: 'Documents', noAttachments: 'No attachments', noAttachmentsHint: 'There are no attachments for this entry.', addAttachment: '＋ Add attachment', openingAttachment: 'Open', attachmentSaving: 'Saving...', attachmentSizeError: 'Each attachment can be a maximum of 10 MB.', attachmentSaveError: 'Attachments could not be saved on this device.',
  account: 'ACCOUNT', loginSync: 'Sign in and sync', accountIntro: 'An AutoLog account lets you securely sync vehicles, entries, and attachments between your devices.', accountUnavailable: 'Sign-in is not set up', accountUnavailableHint: 'This version currently uses local storage on this device only.', login: 'Sign in', information: 'INFORMATION', privacyTerms: 'Privacy and terms', privacy: 'Privacy', privacyTextOne: 'Vehicle information, entries, reminders, and attachments are stored locally on your device. AutoLog does not create an account or send this data to its own server in this version.', privacyTextTwo: 'OBD lookups and workshop searches use external services only when you request them. These services receive only the information needed for the request, such as a trouble code or location.', terms: 'Terms', termsTextOne: 'AutoLog is an overview tool. Reminders and trouble code explanations do not replace a workshop assessment, the manufacturer service schedule, or safety notices.', termsTextTwo: 'You are responsible for backing up local data. Deleting browser or app data may delete locally stored information.', menu: 'MENU', tools: 'Tools', myCarsHint: 'Switch, add, or remove vehicles', loginHint: 'Sync between your devices', language: 'Language', languageHint: 'Choose language for AutoLog', privacyTermsHint: 'How AutoLog handles data', close: 'Close', backHome: 'Back to home', backMenu: 'Back to menu', customizeHome: 'Customize home screen', moreOptions: 'More options', deleteVehicle: 'Delete active vehicle', deleteVehicleConfirm: 'Delete {name} and all entries permanently?', appTitle: 'AutoLog — your vehicle service log', selectedVehicle: 'Selected vehicle', overview: 'Overview', obdInput: 'OBD trouble code', editVehicleInfo: 'Edit vehicle information', nok: 'NOK'
});
Object.assign(translations.nb, { obdFallbackDetail: 'AutoLog har ingen detaljert forklaring på denne koden ennå.', obdFallbackStep: 'Skriv ned koden og symptomene før du sletter den.', obdReading: 'OBD-II-avlesning', obdCode: 'OBD-II-feilkode', noObdDescription: 'OBDex har ingen beskrivelse for denne koden.', repairDifficulty: 'Vanskelighetsgrad: {value}.', diyPossible: 'Dette kan i noen tilfeller gjøres selv.', workshopRecommended: 'Dette bør vurderes eller utføres av verksted.', estimatedHours: 'Anslått arbeidstid: {from}–{to} timer.', workshopDefaultName: 'Verksted' });
Object.assign(translations.en, { obdFallbackDetail: 'AutoLog does not have a detailed explanation for this code yet.', obdFallbackStep: 'Record the code and symptoms before clearing it.', obdReading: 'OBD-II reading', obdCode: 'OBD-II trouble code', noObdDescription: 'OBDex has no description for this code.', repairDifficulty: 'Difficulty: {value}.', diyPossible: 'This may be possible to do yourself in some cases.', workshopRecommended: 'This should be assessed or performed by a workshop.', estimatedHours: 'Estimated labor time: {from}–{to} hours.', workshopDefaultName: 'Workshop' });
const fleetTranslations = { nb: {myVehicles: 'Mine biler', addVehicle: 'Legg til bil', vehicles: 'biler', totalCost: 'totale kostnader', registrations: 'hendelser' }, en: { fleet: 'MY VEHICLES', myVehicles: 'My vehicles', addVehicle: 'Add vehicle', vehicles: 'vehicles', totalCost: 'total costs', registrations: 'events' } };
const dtcLibrary = {
  P0101: ['Ugyldig luftmengdesignal (MAF)', 'Luftmengdemåleren eller luftinntaket gir en verdi utenfor forventet område.', 'Sjekk luftfilter, innsugsslanger og kontakt til luftmengdemåleren.'],
  P0128: ['Motortemperatur under normal driftstemperatur', 'Motoren bruker lengre tid enn forventet på å bli varm.', 'Kontroller kjølevæskenivå og få termostat / temperatursensor vurdert.'],
  P0171: ['Drivstoffblanding for mager (bank 1)', 'Motorstyringen registrerer for mye luft eller for lite drivstoff.', 'Se etter vakuumlekkasje og kontroller luftinntak, MAF-sensor og drivstoffsystem.'],
  P0300: ['Tilfeldig / flere feiltenninger oppdaget', 'Motoren har ujevn forbrenning i én eller flere sylindre.', 'Unngå hard belastning. Verksted bør kontrollere tennplugger, tennspoler, innsprøytning og luftlekkasjer.'],
  P0301: ['Feiltenning i sylinder 1', 'Motorstyringen har registrert ujevn forbrenning i sylinder 1.', 'Kontroller tennplugg og tennspole. Ved blinkende motorlampe: stopp bilen trygt og få hjelp.'],
  P0302: ['Feiltenning i sylinder 2', 'Motorstyringen har registrert ujevn forbrenning i sylinder 2.', 'Kontroller tennplugg og tennspole. Ved blinkende motorlampe: stopp bilen trygt og få hjelp.'],
  P0303: ['Feiltenning i sylinder 3', 'Motorstyringen har registrert ujevn forbrenning i sylinder 3.', 'Kontroller tennplugg og tennspole. Ved blinkende motorlampe: stopp bilen trygt og få hjelp.'],
  P0304: ['Feiltenning i sylinder 4', 'Motorstyringen har registrert ujevn forbrenning i sylinder 4.', 'Kontroller tennplugg og tennspole. Ved blinkende motorlampe: stopp bilen trygt og få hjelp.'],
  P0401: ['For lav EGR-strømning', 'Eksosresirkuleringen har lavere gjennomstrømning enn forventet.', 'La verksted kontrollere EGR-ventil, rør og avleiringer.'],
  P0420: ['Katalysatoreffektivitet under grense (bank 1)', 'Systemet registrerer at katalysatoren renser eksosen dårligere enn forventet.', 'Ikke bytt katalysator kun på grunn av koden. Verksted bør først kontrollere eksoslekkasje, lambdasonder og feiltenning.'],
  P0442: ['Liten lekkasje i fordampningssystemet', 'EVAP-systemet har en liten mulig lekkasje.', 'Kontroller at tanklokket sitter riktig. Kommer koden tilbake, få systemet testet.'],
  P0455: ['Stor lekkasje i fordampningssystemet', 'EVAP-systemet klarer ikke å holde forventet trykk.', 'Sjekk tanklokket først. Hvis det er i orden, bør slanger og ventiler kontrolleres på verksted.'],
  U0100: ['Mistet kommunikasjon med motorstyring', 'En styreenhet får ikke kontakt med motorstyringen over bilens nettverk.', 'Sjekk batterispenning og om flere varsellamper er på. Ved vedvarende feil bør bilen diagnostiseres på verksted.']
};
const obdexUrl = 'https://foerbsnavi.github.io/OBDex/generic.min.json';
const translationUrl = 'https://api.mymemory.translated.net/get';
const defaultReminders = { serviceMonths: 12, serviceKm: 15000, summerTires: 4, winterTires: 10 };
const attachmentDatabase = 'autolog-attachments';
const widgetDefaults = ['reminders', 'logbook', 'obd', 'map'];
let obdexCodesPromise = null;
let attachmentDialogEntryId = null;
let homeWidgets = JSON.parse(localStorage.getItem('bilbok-home-widgets') || 'null') || widgetDefaults;
const translationCache = JSON.parse(localStorage.getItem('bilbok-obdex-no') || '{}');
let data = JSON.parse(localStorage.getItem('bilbok-data') || 'null') || { vehicle: { name: 'Volvo V60', meta: '2019 · AB 12345' }, entries: defaultEntries };
if (!data.vehicles) {
  const vehicleId = data.vehicle?.id || Date.now();
  data = { vehicles: [{ id: vehicleId, ...data.vehicle, entries: data.entries || [] }], activeVehicleId: vehicleId };
  localStorage.setItem('bilbok-data', JSON.stringify(data));
}
let activeFilter = 'all';
let lastDecoded = null;
let language = localStorage.getItem('bilbok-language');
let workshopPlaces = [];
let workshopFilter = 'all';
if (!['nb', 'en'].includes(language)) language = 'nb';
const $ = (id) => document.getElementById(id);
const t = (key) => translations[language]?.[key] || translations.nb[key] || key;
const interpolate = (key, values) => Object.entries(values).reduce((text, [name, value]) => text.replace(`{${name}}`, value), t(key));
const ft = (key) => fleetTranslations[language]?.[key] || fleetTranslations.nb[key] || key;
const activeVehicle = () => data.vehicles.find(vehicle => vehicle.id === data.activeVehicleId) || data.vehicles[0];
const formatDate = (date) => new Intl.DateTimeFormat({ nb: 'nb-NO', en: 'en-GB' }[language], { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(`${date}T12:00:00`));
function reminderSettings(vehicle) { vehicle.reminders = { ...defaultReminders, ...vehicle.reminders }; return vehicle.reminders; }
function mileageValue(value) { return Number(String(value || '').replace(/[^0-9]/g, '')) || 0; }
function addMonths(date, months) { const result = new Date(`${date}T12:00:00`); result.setMonth(result.getMonth() + months); return result; }
function nextTireDate(month) { const now = new Date(); const year = now.getFullYear() + (now.getMonth() + 1 >= month ? 1 : 0); return new Date(year, month - 1, 1, 12); }
function relativeDate(date) { const days = Math.round((date - new Date()) / 86400000); if (days < -7) return t('overdue'); if (days < 0) return t('thisWeek'); if (days === 0) return t('today'); if (days < 31) return interpolate('inDays', { days }); return formatDate(date.toISOString().slice(0, 10)); }
function renderReminders(vehicle, sorted) {
  const settings = reminderSettings(vehicle);
  const lastService = sorted.find(item => item.type === 'service');
  const serviceDate = lastService ? addMonths(lastService.date, Number(settings.serviceMonths)) : null;
  const serviceMileage = lastService ? mileageValue(lastService.mileage) + Number(settings.serviceKm) : 0;
  const reminders = [
    { icon: '🔧', title: t('nextService'), detail: lastService ? `${relativeDate(serviceDate)}${serviceMileage ? ` · ${serviceMileage.toLocaleString({ nb: 'nb-NO', en: 'en-GB' }[language])} km` : ''}` : t('addServiceToStart'), urgent: serviceDate && serviceDate < new Date() },
    { icon: '☀️', title: t('changeSummerTires'), detail: relativeDate(nextTireDate(Number(settings.summerTires))), urgent: false },
    { icon: '❄️', title: t('changeWinterTires'), detail: relativeDate(nextTireDate(Number(settings.winterTires))), urgent: false }
  ];
  $('reminderList').innerHTML = reminders.map(item => `<article class="reminder ${item.urgent ? 'urgent' : ''}"><span>${item.icon}</span><div><strong>${item.title}</strong><small>${item.detail}</small></div></article>`).join('');
}
function renderHomeWidgets() {
  const homePage = $('homePage');
  homeWidgets.forEach(widget => { const element = document.querySelector(`[data-widget="${widget}"]`); if (element) { element.classList.remove('hidden'); homePage.append(element); } });
  document.querySelectorAll('.home-widget').forEach(element => element.classList.toggle('hidden', !homeWidgets.includes(element.dataset.widget)));
}
function attachmentStore(mode = 'readonly') { return new Promise((resolve, reject) => { const request = indexedDB.open(attachmentDatabase, 1); request.onupgradeneeded = () => request.result.createObjectStore('files', { keyPath: 'id' }); request.onerror = () => reject(request.error); request.onsuccess = () => resolve(request.result.transaction('files', mode).objectStore('files')); }); }
async function saveAttachments(vehicleId, entryId, files) { const store = await attachmentStore('readwrite'); const additions = [...files].map(file => new Promise((resolve, reject) => { const request = store.add({ id: `${vehicleId}:${entryId}:${crypto.randomUUID()}`, vehicleId, entryId, name: file.name, type: file.type, blob: file }); request.onsuccess = resolve; request.onerror = () => reject(request.error); })); await Promise.all(additions); }
async function attachmentsForEntry(vehicleId, entryId) { const store = await attachmentStore(); return new Promise((resolve, reject) => { const request = store.getAll(); request.onerror = () => reject(request.error); request.onsuccess = () => resolve(request.result.filter(item => item.vehicleId === vehicleId && item.entryId === entryId)); }); }
async function deleteAttachmentsForEntry(vehicleId, entryId) { const files = await attachmentsForEntry(vehicleId, entryId); const store = await attachmentStore('readwrite'); await Promise.all(files.map(file => new Promise((resolve, reject) => { const request = store.delete(file.id); request.onsuccess = resolve; request.onerror = () => reject(request.error); }))); }
async function showAttachments(entryId) { const vehicle = activeVehicle(); attachmentDialogEntryId = entryId; const files = await attachmentsForEntry(vehicle.id, entryId); $('attachmentTitle').textContent = files.length ? `${files.length} ${t('attachments').toLowerCase()}` : t('noAttachments'); $('attachmentList').innerHTML = files.length ? files.map(file => `<button class="attachment-file" data-file-id="${file.id}"><span>📄</span><strong>${escapeHtml(file.name)}</strong><small>${t('openingAttachment')}</small></button>`).join('') : `<p class="workshop-status">${t('noAttachmentsHint')}</p>`; files.forEach(file => { document.querySelector(`[data-file-id="${file.id}"]`).onclick = () => { const url = URL.createObjectURL(file.blob); window.open(url, '_blank', 'noopener'); setTimeout(() => URL.revokeObjectURL(url), 60000); }; }); if (!$('attachmentDialog').open) $('attachmentDialog').showModal(); }
function updateLanguage() { document.documentElement.lang = language; document.title = t('appTitle'); document.querySelectorAll('[data-language]').forEach(button => button.classList.toggle('active', button.dataset.language === language)); document.querySelectorAll('[data-i18n]').forEach(element => { element.textContent = t(element.dataset.i18n); }); document.querySelectorAll('[data-fleet-i18n]').forEach(element => { element.textContent = ft(element.dataset.fleetI18n); }); document.querySelectorAll('[data-i18n-placeholder]').forEach(element => { element.placeholder = t(element.dataset.i18nPlaceholder); }); document.querySelectorAll('[data-i18n-aria]').forEach(element => { element.setAttribute('aria-label', t(element.dataset.i18nAria)); }); document.querySelectorAll('[data-i18n-title]').forEach(element => { element.title = t(element.dataset.i18nTitle); }); render(); }
function showHomePage() { $('homePage').classList.remove('hidden'); $('fleetPanel').classList.add('hidden'); $('customizeHome').disabled = false; $('addButton').classList.remove('hidden'); }
function showFleetPage() { $('homePage').classList.add('hidden'); $('fleetPanel').classList.remove('hidden'); $('customizeHome').disabled = true; $('addButton').classList.add('hidden'); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function openMenuPanel(panelId) { const panel = $(panelId); if (panel.id === 'fleetPanel') { showFleetPage(); return; } if (panel.dataset.widget) { if (!homeWidgets.includes(panel.dataset.widget)) { homeWidgets.push(panel.dataset.widget); localStorage.setItem('bilbok-home-widgets', JSON.stringify(homeWidgets)); renderHomeWidgets(); } showHomePage(); requestAnimationFrame(() => panel.scrollIntoView({ behavior: 'smooth', block: 'start' })); } }
function persist() { localStorage.setItem('bilbok-data', JSON.stringify(data)); }
function render() {
  const vehicle = activeVehicle();
  $('vehicleName').textContent = vehicle.name; $('vehicleMeta').textContent = vehicle.meta;
  $('entryCount').textContent = vehicle.entries.length;
  const sorted = [...vehicle.entries].sort((a,b) => b.date.localeCompare(a.date));
  $('latestDate').textContent = sorted[0] ? formatDate(sorted[0].date) : '—';
  renderReminders(vehicle, sorted);
  $('removeVehicleButton').disabled = data.vehicles.length === 1;
  const fleetEntries = data.vehicles.flatMap(item => item.entries || []);
  const fleetCost = fleetEntries.reduce((total, item) => total + Number(item.cost || 0), 0);
  $('fleetVehicleCount').textContent = data.vehicles.length;
  $('fleetEntryCount').textContent = fleetEntries.length;
  $('fleetCost').textContent = `${fleetCost.toLocaleString({ nb: 'nb-NO', en: 'en-GB' }[language])} ${t('nok')}`;
  $('fleetList').innerHTML = data.vehicles.map(item => { const entries = item.entries || []; const latest = [...entries].sort((a, b) => b.date.localeCompare(a.date))[0]; return `<button class="fleet-vehicle ${item.id === vehicle.id ? 'active' : ''}" data-vehicle-id="${item.id}"><span>🚙</span><span><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.meta)} · ${entries.length} ${ft('registrations')}</small></span><time>${latest ? formatDate(latest.date) : '—'}</time></button>`; }).join('');
  document.querySelectorAll('.fleet-vehicle').forEach(button => button.onclick = () => { data.activeVehicleId = Number(button.dataset.vehicleId); persist(); render(); });
  const visible = activeFilter === 'all' ? sorted : sorted.filter(item => item.type === activeFilter);
  $('entries').innerHTML = visible.map(item => { const [icon, labelKey] = typeInfo[item.type]; return `<article class="entry"><div class="entry-icon ${item.type}">${icon}</div><div class="entry-main"><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.place || t(labelKey))}${item.mileage ? ` · ${escapeHtml(item.mileage)}` : ''}</p>${item.note ? `<small class="entry-note">${escapeHtml(item.note)}</small>` : ''}<button class="attachment-button" data-attachment-entry-id="${item.id}">📎 ${t('attachments')}</button></div><div class="entry-date"><strong>${formatDate(item.date)}</strong>${item.cost ? `${Number(item.cost).toLocaleString({ nb: 'nb-NO', en: 'en-GB' }[language])} ${t('nok')}` : '—'}</div><button class="delete-entry" data-entry-id="${item.id}" aria-label="${t('deleteEntry')}" title="${t('deleteEntry')}">×</button></article>`; }).join('');
  document.querySelectorAll('.attachment-button').forEach(button => button.onclick = () => showAttachments(Number(button.dataset.attachmentEntryId)));
  $('emptyState').classList.toggle('hidden', visible.length > 0);
  document.querySelectorAll('.delete-entry').forEach(button => button.onclick = () => {
    if (!confirm(t('deleteConfirm'))) return;
    vehicle.entries = vehicle.entries.filter(item => item.id !== Number(button.dataset.entryId));
    deleteAttachmentsForEntry(vehicle.id, Number(button.dataset.entryId)).catch(() => {});
    persist();
    render();
  });
}
function escapeHtml(value) { const el = document.createElement('div'); el.textContent = value; return el.innerHTML; }
$('addButton').onclick = () => { const form = $('entryForm'); form.reset(); form.elements.namedItem('date').valueAsDate = new Date(); $('entryDialog').showModal(); };
$('editVehicle').onclick = () => { const vehicle = activeVehicle(); const form = $('vehicleForm'); form.elements.namedItem('name').value = vehicle.name; form.elements.namedItem('meta').value = vehicle.meta; $('vehicleDialog').showModal(); };
$('addVehicleButton').onclick = () => { $('addVehicleForm').reset(); $('addVehicleDialog').showModal(); };
$('fleetBack').onclick = showHomePage;
$('editReminders').onclick = () => { const settings = reminderSettings(activeVehicle()); const form = $('reminderForm'); Object.entries(settings).forEach(([key, value]) => { form.elements.namedItem(key).value = value; }); $('reminderDialog').showModal(); };
$('customizeHome').onclick = () => { const form = $('widgetForm'); widgetDefaults.forEach(widget => { form.elements.namedItem(widget).checked = homeWidgets.includes(widget); }); $('widgetDialog').showModal(); };
document.querySelectorAll('dialog .close').forEach(button => button.onclick = () => button.closest('dialog').close());
document.querySelectorAll('dialog').forEach(dialog => dialog.addEventListener('click', event => { if (event.target === dialog) dialog.close(); }));
document.querySelectorAll('.menu-back').forEach(button => button.onclick = () => { button.closest('dialog').close(); $('appMenu').showModal(); });
document.querySelectorAll('[data-language]').forEach(button => button.onclick = () => { language = button.dataset.language; localStorage.setItem('bilbok-language', language); updateLanguage(); });
$('addAttachmentButton').onclick = () => $('attachmentPicker').click();
$('attachmentPicker').onchange = async (event) => { const files = [...event.target.files]; event.target.value = ''; if (!attachmentDialogEntryId || !files.length) return; if (files.some(file => file.size > 10 * 1024 * 1024)) { alert(t('attachmentSizeError')); return; } const button = $('addAttachmentButton'); button.disabled = true; button.textContent = t('attachmentSaving'); try { await saveAttachments(activeVehicle().id, attachmentDialogEntryId, files); await showAttachments(attachmentDialogEntryId); } catch { alert(t('attachmentSaveError')); } finally { button.disabled = false; button.textContent = t('addAttachment'); } };
$('removeVehicleButton').onclick = () => { if (data.vehicles.length === 1) return; const vehicle = activeVehicle(); if (!confirm(interpolate('deleteVehicleConfirm', { name: vehicle.name }))) return; data.vehicles = data.vehicles.filter(item => item.id !== vehicle.id); data.activeVehicleId = data.vehicles[0].id; persist(); render(); };
$('filterButton').onclick = () => $('filterRow').classList.toggle('hidden');
document.querySelectorAll('.chip').forEach(button => button.onclick = () => { activeFilter = button.dataset.filter; document.querySelectorAll('.chip').forEach(c => c.classList.toggle('active', c === button)); render(); });
$('entryForm').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const files = form.getAll('attachments').filter(file => file.size); if (files.some(file => file.size > 10 * 1024 * 1024)) { alert(t('attachmentSizeError')); return; } const entry = { id: Date.now(), type: form.get('type'), title: form.get('title').trim(), date: form.get('date'), mileage: form.get('mileage') ? `${Number(form.get('mileage')).toLocaleString({ nb: 'nb-NO', en: 'en-GB' }[language])} km` : '', place: form.get('place').trim(), cost: form.get('cost') || 0, note: form.get('note').trim() }; try { if (files.length) await saveAttachments(activeVehicle().id, entry.id, files); activeVehicle().entries.push(entry); persist(); $('entryDialog').close(); render(); } catch { alert(t('attachmentSaveError')); } });
$('reminderForm').addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); activeVehicle().reminders = Object.fromEntries(Object.keys(defaultReminders).map(key => [key, Number(form.get(key))])); persist(); $('reminderDialog').close(); render(); });
$('widgetForm').addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); homeWidgets = widgetDefaults.filter(widget => form.get(widget) === 'on'); localStorage.setItem('bilbok-home-widgets', JSON.stringify(homeWidgets)); $('widgetDialog').close(); renderHomeWidgets(); });
$('vehicleForm').addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); Object.assign(activeVehicle(), { name: form.get('name').trim(), meta: form.get('meta').trim() }); persist(); $('vehicleDialog').close(); render(); });
$('addVehicleForm').addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const vehicle = { id: Date.now(), name: form.get('name').trim(), meta: form.get('meta').trim(), entries: [] }; data.vehicles.push(vehicle); data.activeVehicleId = vehicle.id; persist(); $('addVehicleDialog').close(); render(); });
function categoryForCode(code) { return t('categories')[code[0]]; }
function loadObdexCodes() {
  if (!obdexCodesPromise) {
    obdexCodesPromise = fetch(obdexUrl).then(response => {
      if (!response.ok) throw new Error(`OBDex svarte med ${response.status}`);
      return response.json();
    }).then(codes => new Map(codes.map(item => [item.code, item]))).catch(() => null);
  }
  return obdexCodesPromise;
}
async function translateToNorwegian(text) {
  if (!text) return text;
  if (translationCache[text] && translationCache[text] !== text) return translationCache[text];
  try {
    const url = new URL(translationUrl);
    url.searchParams.set('q', text);
    url.searchParams.set('langpair', 'en|no');
    const response = await fetch(url);
    const result = await response.json();
    const translated = result.responseData?.translatedText;
    if (translated && translated !== text) {
      translationCache[text] = translated;
      localStorage.setItem('bilbok-obdex-no', JSON.stringify(translationCache));
      return translated;
    }
  } catch { }
  return text;
}
async function obdexInfo(item) {
  const sourceLanguage = 'en';
  const title = item.title?.[sourceLanguage] || item.title?.en || item.title?.de || t('obdCode');
  const description = item.description?.[sourceLanguage] || item.description?.en || item.description?.de || t('noObdDescription');
  const causes = (item.common_causes || []).map(cause => cause.label?.[sourceLanguage] || cause.label?.en || cause.label?.de).filter(Boolean);
  const symptoms = (item.symptoms || []).map(symptom => symptom[sourceLanguage] || symptom.en || symptom.de).filter(Boolean);
  const repair = item.repair || {};
  const repairParts = [];
  if (repair.difficulty) repairParts.push(interpolate('repairDifficulty', { value: repair.difficulty }));
  if (repair.diy_possible === true) repairParts.push(t('diyPossible'));
  if (repair.diy_possible === false) repairParts.push(t('workshopRecommended'));
  if (repair.estimated_hours?.length === 2) repairParts.push(interpolate('estimatedHours', { from: repair.estimated_hours[0], to: repair.estimated_hours[1] }));
  if (language !== 'nb') return { title, detail: description, nextStep: repairParts.join(' ') || 'Record the code and symptoms before clearing it.', causes, symptoms, solution: repairParts.join(' ') };
  const [norwegianTitle, norwegianDescription, norwegianCauses, norwegianSymptoms] = await Promise.all([translateToNorwegian(title), translateToNorwegian(description), Promise.all(causes.map(translateToNorwegian)), Promise.all(symptoms.map(translateToNorwegian))]);
  return { title: norwegianTitle, detail: norwegianDescription, nextStep: repairParts.join(' ') || 'Skriv ned koden og symptomene før du sletter den. Få bilen vurdert hvis feilen kommer tilbake.', causes: norwegianCauses, symptoms: norwegianSymptoms, solution: repairParts.join(' ') };
}
function detailList(title, items) { return items.length ? `<div class="decode-detail"><h4>${title}</h4><ul>${items.map(item => `<li>${escapeHtml(item)}</li>`).join('')}</ul></div>` : ''; }
function showDecode(code, info) { const normalized = Array.isArray(info) ? { title: info[0], detail: info[1], nextStep: info[2], causes: [], symptoms: [], solution: '' } : info; lastDecoded = { code, title: normalized.title, detail: normalized.detail }; $('decodeResult').innerHTML = `<div class="result-topline"><span class="result-code">${code}</span><span>${categoryForCode(code)}</span></div><h3>${escapeHtml(normalized.title)}</h3><p>${escapeHtml(normalized.detail)}</p>${detailList(t('symptoms'), normalized.symptoms)}${detailList(t('causes'), normalized.causes)}<p class="next-step"><strong>${t('solution')}:</strong> ${escapeHtml(normalized.nextStep)}</p><button class="save-dtc" id="saveDtcButton">${t('saveDtc')}</button>`; $('decodeResult').classList.remove('hidden'); $('saveDtcButton').onclick = saveDtcToLog; }
async function decodeDtc() { const code = $('dtcInput').value.trim().toUpperCase().replace(/\s/g, ''); $('dtcInput').value = code; if (!/^[PBCU][0-9A-F]{4}$/.test(code)) { $('decodeResult').innerHTML = `<p>${t('invalidCode')} <strong>P0420</strong>.</p>`; $('decodeResult').classList.remove('hidden'); return; } const fallback = [t('genericCode'), t('obdFallbackDetail'), t('obdFallbackStep')]; const localInfo = dtcLibrary[code]; if (localInfo && language === 'nb') { showDecode(code, localInfo); return; } $('decodeButton').disabled = true; $('decodeButton').textContent = t('translating'); $('decodeResult').innerHTML = `<p>${t('loading')}</p>`; $('decodeResult').classList.remove('hidden'); const codes = await loadObdexCodes(); const obdexMatch = codes?.get(code); showDecode(code, obdexMatch ? await obdexInfo(obdexMatch) : fallback); $('decodeButton').disabled = false; $('decodeButton').textContent = t('decodeButton'); }
function saveDtcToLog() { if (!lastDecoded) return; activeVehicle().entries.push({ id: Date.now(), type: 'other', title: `${lastDecoded.code} · ${lastDecoded.title}`, date: new Date().toISOString().slice(0, 10), mileage: '', place: t('obdReading'), cost: 0, note: lastDecoded.detail }); persist(); render(); $('saveDtcButton').textContent = t('savedDtc'); $('saveDtcButton').disabled = true; }
function distanceInKm(latitude, longitude, place) { const radians = Math.PI / 180; const latitudeDelta = (place.latitude - latitude) * radians; const longitudeDelta = (place.longitude - longitude) * radians; const a = Math.sin(latitudeDelta / 2) ** 2 + Math.cos(latitude * radians) * Math.cos(place.latitude * radians) * Math.sin(longitudeDelta / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }
function renderWorkshops() { const visible = workshopPlaces.filter(place => workshopFilter === 'all' || (workshopFilter === 'dealer' ? place.isDealer : !place.isDealer)); $('workshopResults').innerHTML = visible.length ? visible.map(place => `<a class="workshop-result" href="https://www.openstreetmap.org/?mlat=${place.latitude}&mlon=${place.longitude}#map=17/${place.latitude}/${place.longitude}" target="_blank" rel="noopener"><span><strong>${escapeHtml(place.name)}</strong><small>${escapeHtml(place.address || t('addressUnavailable'))} · ${place.isDealer ? t('dealer') : t('independent')}</small></span><em>${place.distance.toFixed(1)} km</em></a>`).join('') : `<p class="workshop-status">${t('noWorkshopMatches')}</p>`; }
async function findWorkshops(position) { const { latitude, longitude } = position.coords; $('locateWorkshops').disabled = true; $('locateWorkshops').textContent = t('locating'); $('workshopStatus').textContent = t('searchingWorkshops'); const query = `[out:json][timeout:25];(nwr(around:15000,${latitude},${longitude})["shop"="car_repair"];nwr(around:15000,${latitude},${longitude})["amenity"="car_repair"];);out center tags;`; try { const response = await fetch('https://overpass-api.de/api/interpreter', { method: 'POST', body: `data=${encodeURIComponent(query)}` }); if (!response.ok) throw new Error('Search failed'); const result = await response.json(); const seen = new Set(); workshopPlaces = result.elements.map(item => { const itemLatitude = item.lat || item.center?.lat; const itemLongitude = item.lon || item.center?.lon; const tags = item.tags || {}; return itemLatitude && itemLongitude ? { name: tags.name || t('workshopDefaultName'), address: [tags['addr:street'], tags['addr:housenumber'], tags['addr:city']].filter(Boolean).join(' '), isDealer: Boolean(tags.brand || tags['brand:wikidata']), latitude: itemLatitude, longitude: itemLongitude } : null; }).filter(Boolean).filter(place => { const key = `${place.name}-${place.latitude}-${place.longitude}`; if (seen.has(key)) return false; seen.add(key); place.distance = distanceInKm(latitude, longitude, place); return true; }).sort((a, b) => a.distance - b.distance).slice(0, 20); const box = .08; $('workshopMap').src = `https://www.openstreetmap.org/export/embed.html?bbox=${longitude - box}%2C${latitude - box}%2C${longitude + box}%2C${latitude + box}&layer=mapnik&marker=${latitude}%2C${longitude}`; $('workshopMap').classList.add('visible'); $('workshopFilters').hidden = false; $('workshopStatus').textContent = workshopPlaces.length ? interpolate('workshopFound', { count: workshopPlaces.length }) : t('noWorkshops'); renderWorkshops(); } catch { $('workshopStatus').textContent = t('workshopError'); } finally { $('locateWorkshops').disabled = false; $('locateWorkshops').textContent = t('locateMe'); } }
$('locateWorkshops').onclick = () => { if (!navigator.geolocation) { $('workshopStatus').textContent = t('locationUnsupported'); return; } $('workshopStatus').textContent = t('gettingLocation'); navigator.geolocation.getCurrentPosition(findWorkshops, error => { const message = { 1: t('locationDenied'), 2: t('locationUnavailable'), 3: t('locationTimeout') }[error.code] || t('workshopError'); $('workshopStatus').textContent = message; }, { enableHighAccuracy: false, timeout: 10000, maximumAge: 300000 }); };
document.querySelectorAll('.workshop-filter').forEach(button => button.onclick = () => { workshopFilter = button.dataset.workshopFilter; document.querySelectorAll('.workshop-filter').forEach(item => item.classList.toggle('active', item === button)); renderWorkshops(); });
$('decodeButton').onclick = decodeDtc;
$('dtcInput').addEventListener('keydown', (event) => { if (event.key === 'Enter') { event.preventDefault(); decodeDtc(); } });
$('moreButton').onclick = () => $('appMenu').showModal();
$('closeMenu').onclick = () => $('appMenu').close();
document.querySelectorAll('.menu-option[data-panel], .menu-option[data-dialog]').forEach(button => button.onclick = () => { $('appMenu').close(); if (button.dataset.dialog) { $(button.dataset.dialog).showModal(); return; } openMenuPanel(button.dataset.panel); });
renderHomeWidgets();
updateLanguage();
